flightaware/tohil

README.md, pysrc/tohil/__init__.py, pysrc/tohil/shadowdict.py
Shadow Dictionaries, aka ShadowDicts, create a python dict-like object that shadows a Tcl array.
Assume we have an array "x" in Tcl that we want to shadow as a dictionary "x" in Python, we would write `x = tohil.ShadowDict("x")`
Once created, the shadowdict can be gotten as a string using str() or print(), etc.
Elements can be read form the python side using dictionary notation, for example `x['d']`, set in a standard way (`x['e'] = '5'`), and deleted using del (`del x['e']`).  Also you can iterate on the keys as with dicts.
Changes made from the Python side occur on the Tcl side, and all accesses, traversals, etc, are made using the Tcl array.  In other words, ShadowDicts never cache values from the Tcl array on the python side.
=> Shadow Dictionaries

TCLOBJECTS.md, generic/tohil.c, tests/test_td_iter.py
You can now iterate over a TD with td_iter. For example, something like:
```
t = tohil.tclobj("a 1 b 2 c 3 d 4 e 5 f 6")
for i in t.td_iter():
print(i)
```
If you pass a to= conversion to td_iter, the iterator returns tuples comprising the key and the value as well, with the value converted to the to= conversion.
```
for key, value in t.td_iter(to=int):
print(f"key {key} value {value}")
```
=> td_iterator method is an iterator over tclobj tcl dicts

generic/tohil.c, tests/test_tcldict.py, tests/test_tclobj.py
Allow tclobj and tcldict types to accept an option to=type parameter at object creation type, and provide a "to" member that can be get and set, obj.to=str, etc, to one of our accepted datatypes.  This is cool.
=> to= option for tclobj and tcldict object creation, setting "to" as a member of those objects

KNOTES.md, configure.ac, generic/tohil.c, tests/test_tclobj.py, tests/test_tclobj_math.py
This adds "number support" for tohil's tclobj python data type.  As a result, tclobjs having proper contents can be used in numeric calculations for arithmetic, bitwise or, and, and xor, left and right shift, invert, negative, positive, aobsolute value, etc.  In the below, t or val or both can be tclobjs.
* `t + val`
* `t - val`
* `t * val`
* `t % val`
* `t / val`
* `t // val`
* `t | val`
* `t &= val`
* `t <<= val`
* `t >>= val`
* `t ^= val`
Also in-place methods are support, so tohil tclobjs can be the source or destination of expressions such as `a += b`, etc.  `+=` can also be used for concatenation when number addition fails due to the contents of the values.  In the below, t is always a tclobj, and val can be a tclobj as well as a python int in all cases and a python float in certain …
=> More tclobj

generic/tohil.c
tclobjs can now shadow a tcl variable or array element such that if created with the var=varname argument, every access of tclobj's underlying tcl object will be made from the tcl variable, and every store to it will be stored into the tcl variable.
=> Tclobj var

generic/tohil.c, tests/test_convert.py, tests/test_tclobj_math.py, tests/test_tclobj_varsync.py
* Handle attempted division by zero in divide, floor divide, divmod and remainder by raising a division by zero exception instead of getting a C-level floating point exception, resulting in a SIGFPE.
* Start using the "hypothesis" python testing module for many tests.  Hypothesis is good stuff™.  We already found and fixed some problems because of it.
=> Raise division-by-zero exceptions instead of causing SIGFPEs on divide by zero; Hypothesis

KNOTES.md, Makefile.in, generic/tohil.c, pysrc/tohil/__init__.py, tests/test_shadowdict.py, tests/test_tclobj.py, tests/test_td.py
* .reset() method renamed to .clear() for conformance with the rest of python.
* Likewise .lappend() and .lappend_list() were renamed to .append() and .extend().
* New .pop() method for tclobjs
* New __getitem__ method for tcldict.
* tcldict.keys(), .values() and .items() sort of works but not really insofar as they are not mutable.
* really nice repr() function for tcldict iterators
* Make ShadowDicts behave more like dicts
* conform ShadowDict "get" method to behave like dict's does, i.e.
has optional default argument, returns None if key isn't there and
default isn't specified.
* new "clear" method removes all items from the shadow dictionary, i.e.
unsets the tcl array.
=> Tcldict and tclobj improvements

pysrc/tohil/__init__.py
Catches a broader list and shouldn't require maintenance down the line.
=> Use stdlib for Python keyword check

generic/tohil.c
Somehow I managed to define two related but different functions with almost the same name.
This PR only renames the functions consistently with the underlying Tcl functions they're based on.
=> Disambiguate function names tohil_UTF8toTcl and tohil_UTF8ToTcl.

generic/tohil.c
Prior to this PR, tohil used single-phase init and had some global pointers that it maintained.  This prevented tohil from being used in subinterpreters.
This PR switches tohil to use multi-phase init and to get rid of all the globals.
As a result, tohil should now work within subinterpreters.
=> Multiphase init

KNOTES.md, generic/tohil.c, tests/subinterpreters.test, tests/tohil.test
This PR makes tohil work properly with Python subinterpreters.  Further, it leverages them; when a second and any subsequent Tcl interpreters in a single process do a `package require tohil`, a new Python subinterpreter is created for each one.
This required making tohil's Python extension side support multi-phase initialization, and for Tohil to have a way to tell by looking at a Tcl interpreter whether it had a Python interpreter attached, and if so to get its thread state.
This keeps the Python work that each Tcl intepreter running in a single process does, separate.  One nice benefit is that the Apache Rivet module for Tcl when run in "separate virtual interpreter" mode, where each vhost gets a separate Tcl interpreter, works properly.
=> Support for Python subinterpreters

.gitignore, Doc/Makefile, Doc/reference/index.rst, Doc/tools/templates/indexcontent.html, Doc/tutorial/intro.rst, Doc/tutorial/tohil_python.rst, Doc/tutorial/tohil_tcl.rst, Doc/whatsnew/3.2.rst, Doc/whatsnew/4.0.rst, Doc/whatsnew/index.rst, KNOTES.md, README.Linux, configure.ac, generic/tohil.c, pysrc/tohil/__init__.py, tests/test_eval.py, tests/test_tclobj.py
* to= conversions now default to tohil.tclobj instead of str when none is specified.
* python subinterpreters are now deleted when the associated tcl interpreter is deleted.
* version bump to 4.0.0 (but 4.0.0 hasn't been released yet.)
* greatly improved documentation.
=> return tclobjs by default; python subinterpreter handling improvements; much improved docs; version bump

Doc/README.md, Doc/reference/tohil_types.rst, Doc/tutorial/tohil_python.rst, Doc/whatsnew/4.0.rst, generic/tohil.c, pysrc/tohil/__init__.py, tests/tohil.test
* iterating on a tclobj would result in a leaked reference of the tcl  list object.  that is now fixed.  that also caused some strange  behavior.
* new tohil.result() python-side function returns the interpreter result object.
* stop propagating tcl -errorstack into TclError object  (The Tcl errorstack is big and replicates info already included in the rest of the TclError object.  This removes it.  It makes the TclError object considerably more manageable to the human trying to look at it.
* improvements in error messages when Tcl errors are raised as Python exceptions by Tohil.
* numerous improvements to the documentation.
=> tclobj iterator leak fix; new tohil.result function; error message improvements; improved docs

Doc/reference/tohil_tcl_functions.rst, Doc/tutorial/tohil_tcl.rst, generic/tohil.c, tests/tohil.test
For each argument to a Python function called from Tcl using
tohil::call, if the value of the argument is the special sentinel
"tohil::NONE", tohil::call will pass the python None object that
argument's value.
Fix for #37
=> Provide a way to pass None when using tohil::call

generic/tohil.c, tests/test_tclvars.py
fix improper overwrites for tclobj methods when the object is bound to a var (tclvar)
There were errors in how tclvars (tclobjs bound to vars) handled some methods such as insert, pop, append, and extend, resulting in the data getting overwritten
We introduce a new routine, TohilTclObj_objptr_for_write, that returns a TclObj * that we can mutate.  It is either from the tclobj object directly or from the tcl variable defined in the tclobj (tclvar), and it's been pre-checked to see if it's shared and if it is, it's been duplicated properly such that we can mutate it (it is no longer shared.)
We also subsume a couple places where tohil C code "got it right" but in an ad hoc manner with calls to the new function.
fixes issue #38
=> tclvar fixes

generic/tohil.c
Make values of tclobj.as_dict() and to=dict conversions be tclobj objects instead of strings.
Fix for issue #40
=> Dict values as tclobjs

generic/tohil.c, tests/tohil.test
The Tcl-side tohil::call function provides a way to call a Python
function while making sure that the arguments passed to the function
are not interpreted by Python.
Because it didn't look in builtins if it couldn't find
the function in dunder main, stuff like "tohil::call print foo"
didn't work.
We now look in builtins after exhausting our other options.
Thanks to Oliver Jowett (obj) for a consult.
Fixes issue #39.
=> make tohil::call support builtins

generic/tohil.c, tests/test_tclobj.py
They should simply return themselves. Fortunately Python's got a helper
for that. Fixes #34.
=> Correct behavior of __iter__() on iterators

Doc/reference/tohil_python_functions.rst, generic/tohil.c, pysrc/tohil/__init__.py, tests/test_register.py
Mostly cribbed from tkinter which has similar functionality. Useful in event loop cases where a Tcl callback can be specified.
=> Allow for directly linking Tcl commands to Python functions

generic/tohil.c, pkgIndex.tcl.in
Support "package forget tohil; package require tohil" by migrating from using Tcl_PkgProvide in the C code to using "package provide" in pkgIndex.tcl.in.
Also adds support for unloading the shared library using Tcl's "unload" command.
Hat tip to @pooryorick for the bug report and the solution.
Fixes Issue #52
=> Make "package forget tohil; package require tohil" work and allow the shared library to be unloaded using Tcl's "unload"

generic/tohil.c, tests/test_register.py
At the point in PythonCmd where a null result was checked and TCL_ERROR returned, it instead ineeded to `return Tohil_ReturnExceptionToTcl(interp, "error in python object call");` to get all the stuff necessary to dig out the Python exception and return it as a Tcl error.
This fixes issue 57.
=> conform register_callback returns to standard practice

Doc/reference/tohil_tcl_functions.rst, Doc/tutorial/tohil_tcl.rst, generic/tohil.c, tests/tohil.test
Add an option "-nonevalue" to tohil::call to allow alternate none-value strings to be used.
=> BCK-6282 Improve the handling of None values from the Tcl interface for tohil

Doc/reference/tohil_tcl_functions.rst, generic/tohil.c, tests/tohil.test
Fix for #48 "Running multiple lines of python via tohil::exec/eval is a bit clunky"
The un-indenter can handle mixed spaces and tabs but only if the combination of spaces and tabs is identical on every non-blank line. It makes no assumptions as to tab-stop settings, it just requires the exact same combination as the first indented line.
It does not apply to tohil::eval calls.
It treats all unicode multibyte sequences as non-blank and copies them verbatim.
=> BCK-6281 Implement an un-indenter for embedded Python code passed to tohil::exec

generic/tohil.c, pysrc/tohil/__init__.py
Tohil stored a Python capsule in dunder-main.interp and you could make Python crash by doing like "interp = ''" before importing tohil.  This renames interp to _tohil_interp, which is way less likely to have a conflict.
We also do a bit of cleanup on the name of the Python capsule itself.
Fixes issue #63.
=> Issue 63 rename interp

configure.ac
Nix passes 3.7 as its version, not 3.7m. We can get at the m with
--abiflags, though. This ensures that when building the Tcl .so, we
provide the proper -l flag.
I'm not so good with autoconf, so this is probably not the ideal way to implement such a fix. @lehenbauer do you have a better place to put this?
=> Fix building against Python 3.7 with nix

configure.ac, generic/tohil.c
For every function of the tohil Tcl-side that does something with Python such as exec'ing, eval'ing, importing, call'ing, or invoking a Tcl/Python callback, don't just switch to the threadstate for that tcl interpreter's corresponding Python interpreter, but also keep track of what the threadstate is when those functions are first called, and switch it back right before they return.
To do this we
* made tohil_setup_subinterp return the prior python thread state.
* extended the calls to tohil_setup_subinterp in Tohil_Init to keep the prior thread state and, prior to returning, to restore it.
* added a PyThreadState parameter to each ot tohil_tcl_return, Tohil_ReturnTclError, Tohil_ReturnStartupExceptionToTcl, and Tohil_ReturnExceptionToTcl and code for them to either pass along or restore …
=> Thread state handling improvements aka bug and crash fixes when using Tohil/Python from multiple Tcl interpreters

Makefile.in, setup.py.in
Not sure why we had the $(bindir) python prefix, to support multiple
installed pythons perhaps? @lehenbauer is this going to upset stuff
that doesn't use nix?
=> Enable running tests via nix

Doc/reference/tohil_types.rst, generic/tohil.c, pysrc/tohil/__init__.py, tests/test_tclobj_math.py
* Perform all integer operations using Tohil tclobj objects using 64-bit integers, even on 32-bit machines. (It was already 64-bits on 64-bit machines.)
* When creating a new Tcl numeric object from a numeric Python object, we now do so much more efficiently (see below).
* Make TclProcs default to returning tclobj data type instead of string. (Fixes issue #72)
* Expanded number ranges for hypothesis framework testing of tclobj math.
When creating a new Tcl object from a numeric Python object, previously tohil always converted it to a string, which thereby supported both Tcl and Python's arbitrary precision arithmetic, but would be slower than using access functions that worked on machine-native numeric types when those types were large enough to handle the numbers being represented. …
=> Tohil tclobj integer math always at 64 bits; Faster Python-to-Tcl numeric conversions; TclProcs now return tclobj by default

tests/test_tclobj_math.py
Hypothesis caught this. Can't go to 2**64 with tclobj
=> Fix leftshift test that exceeds 63 bits

pysrc/tohil/__init__.py, tests/test_arg_globals.py
Helps Tcl behave like it's running in a shell.
=> Set ::argv globals for Tcl if Python has anything in sys.argv

pysrc/tohil/__init__.py, tests/test_arg_globals.py
1. In python 3.8+, sys.argv defaults to [""] when not otherwise set (I
had wrongly assumed it would always be [])
2. If Tcl's ::arg* vars were already set naturally, tohil could clear
them improperly.
EP-90
=> Fix a couple issues with setting Tcl's ::arg* vars

.github/workflows/linux-ci.yml, generic/tohil.c, tests/tohil.test
* This update aligns Tohil's tclobj math behavior for both floor division (//) and remainder (%) operations with CPython, eliminating small platform-dependent calculation differences, for example between x86 and ARM.  It applies consistently to expressions (e.g., a // b, a % b) and augmented assignments (e.g., a //= b, a %= b).
* In Tohil_Init, use Python's PyConfig means of configuring the Python interpreter in place of the deprecated Py_SetProgramName.
* Also when Tcl is the parent, use PyConfig's mechanism for telling Python not to install signal handlers.
This should be compatible with Python versions back to and including 3.8.
* Make Tohil_TD_iter_repr declare its proper argument type, the actual iterator type that goes with it, Tohil_TD_IterObj.
* Conform Tohil_TD_iter_repr to …
=> Fix floating point platform discrepancies; replace deprecated call to Py_SetProgramName; Remove ref to internal python type
